// <auto-generated />
using System;
using Autoparts.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Autoparts.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503205327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoparts.Domains.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Category = "filters", ImageUrl = "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=300&h=200&fit=crop", Name = "Масляный фильтр Mann", Price = 450m, Stock = 50 },
                        new { Id = 2, Category = "filters", ImageUrl = "https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=300&h=200&fit=crop", Name = "Воздушный фильтр Bosch", Price = 380m, Stock = 40 },
                        new { Id = 3, Category = "brakes", ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop", Name = "Тормозные колодки Brembo", Price = 2800m, Stock = 20 },
                        new { Id = 4, Category = "brakes", ImageUrl = "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=300&h=200&fit=crop", Name = "Тормозной диск TRW", Price = 3200m, Stock = 15 },
                        new { Id = 5, Category = "suspension", ImageUrl = "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=300&h=200&fit=crop", Name = "Амортизатор KYB передний", Price = 4500m, Stock = 10 },
                        new { Id = 6, Category = "suspension", ImageUrl = "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=300&h=200&fit=crop", Name = "Пружина подвески Monroe", Price = 2100m, Stock = 12 },
                        new { Id = 7, Category = "engine", ImageUrl = "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=300&h=200&fit=crop", Name = "Свечи зажигания NGK (4 шт)", Price = 1200m, Stock = 60 },
                        new { Id = 8, Category = "engine", ImageUrl = "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=300&h=200&fit=crop", Name = "Ремень ГРМ Gates", Price = 1800m, Stock = 25 },
                        new { Id = 9, Category = "engine", ImageUrl = "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=300&h=200&fit=crop", Name = "Моторное масло Castrol 5W-40 (4л)", Price = 2600m, Stock = 30 },
                        new { Id = 10, Category = "electrical", ImageUrl = "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=300&h=200&fit=crop", Name = "Аккумулятор Varta 60Ah", Price = 8500m, Stock = 8 },
                        new { Id = 11, Category = "electrical", ImageUrl = "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=300&h=200&fit=crop", Name = "Генератор Bosch", Price = 12000m, Stock = 5 },
                        new { Id = 12, Category = "electrical", ImageUrl = "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=300&h=200&fit=crop", Name = "Лампа H7 Philips (2 шт)", Price = 650m, Stock = 45 });
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.CartItem", b =>
                {
                    b.HasOne("Autoparts.Domains.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoparts.Domains.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                    b.Navigation("User");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.Order", b =>
                {
                    b.HasOne("Autoparts.Domains.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.OrderItem", b =>
                {
                    b.HasOne("Autoparts.Domains.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoparts.Domains.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.Product", b =>
                {
                    b.Navigation("CartItems");
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Autoparts.Domains.Entities.User", b =>
                {
                    b.Navigation("CartItems");
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
